/* ------------------------------------------------------------------------
 * android/app/build.gradle.kts  (Kotlin-DSL)
 * ---------------------------------------------------------------------- */

import java.util.Properties

// -----------------------------------------------------------------------
// 1.  Load keystore credentials from android/key.properties
// -----------------------------------------------------------------------
val keystoreProps = Properties().apply {
    // key.properties must sit next to this build script (android/key.properties)
    load(rootProject.file("key.properties").inputStream())
}

// -----------------------------------------------------------------------
// 2.  Gradle plugins
// -----------------------------------------------------------------------
plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must come last.
    id("dev.flutter.flutter-gradle-plugin")
}

// -----------------------------------------------------------------------
// 3.  Android configuration
// -----------------------------------------------------------------------
android {
    namespace       = "com.catastrophecompanion.app.catastrophe_companion"
    compileSdk      = flutter.compileSdkVersion
    ndkVersion      = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        applicationId = "com.catastrophecompanion.app.catastrophe_companion"
        minSdk        = flutter.minSdkVersion
        targetSdk     = flutter.targetSdkVersion
        versionCode   = flutter.versionCode     // comes from pubspec.yaml
        versionName   = flutter.versionName
    }

    // -------------------------------------------------------------------
    // 3a.  Upload-keystore definition
    // -------------------------------------------------------------------
    signingConfigs {
        create("release") {
            storeFile      = file(keystoreProps["storeFile"] as String)
            storePassword  = keystoreProps["storePassword"] as String
            keyAlias       = keystoreProps["keyAlias"] as String
            keyPassword    = keystoreProps["keyPassword"] as String
        }
    }

    // -------------------------------------------------------------------
    // 3b.  Build types
    // -------------------------------------------------------------------
    buildTypes {
        getByName("debug") {
            // uses default debug keystore
            isMinifyEnabled   = false
            isShrinkResources = false
        }

        getByName("release") {
            signingConfig     = signingConfigs.getByName("release")
            isMinifyEnabled   = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
}

// -----------------------------------------------------------------------
// 4.  Flutter source location (auto-generated by the template)
// -----------------------------------------------------------------------
flutter {
    source = "../.."
}